### ISSUE TITLE
Handle data files for filing documents

### ISSUE THREAD

**Issue by iangow** [iangow-public/edgar#12]
IF you look [here](https://www.sec.gov/Archives/edgar/data/1527666/000107878212002654/0001078782-12-002654-index.htm) you will see that there are two groups of "filing documents".

As seen [here](https://github.com/iangow-public/edgar/blob/master/readme.md), the code in [get_filing_docs.R](https://github.com/iangow-public/edgar/blob/master/get_filing_docs.R) only extracts the first table. For now, we should examine how easy it is to modify the function `get_filing_docs()` to handle these cases. (I think it will be possible to identify the cases with this issue so that we don't have to scrape everything again.)

**Comment by bdcallen** [comment]
Here is code to delete the problem cases idenfied by mismatches between `seq` and the number of filings. We have already run this code, so the problem files are now gone.

```r
library(dplyr, warn.conflicts = FALSE)
library(RPostgreSQL, quietly = TRUE)

pg <- dbConnect(PostgreSQL())

rs <- dbExecute(pg, "SET search_path TO edgar")
rs <- dbExecute(pg, "SET work_mem TO '10GB'")

filing_docs <- tbl(pg, "filing_docs")

problems <-
    filing_docs %>%
    group_by(file_name) %>%
    summarise(max_seq = max(seq, na.rm = TRUE),
              n_docs = n()) %>%
    mutate(problem = max_seq > n_docs) %>%
    filter(problem) %>%
    ungroup() %>%
    compute(name = "problems", temporary = FALSE,
            indexes = "file_name")

problems %>% count(problem)

filing_docs <- tbl(pg, "filing_docs")
problems <- tbl(pg, "problems")

problems %>%
    inner_join(filing_docs) %>%
    summarise(n_fs = n_distinct(file_name))

dbGetQuery(pg, "
    BEGIN;
    DELETE FROM edgar.filing_docs 
          WHERE file_name IN (SELECT file_name FROM edgar.problems)")
dbGetQuery(pg, "COMMIT; ")
dbGetQuery(pg, "DROP TABLE IF EXISTS edgar.problems; ")

problems %>%
    inner_join(filing_docs) %>%
    summarise(n_fs = n_distinct(file_name))

dbDisconnect(pg)
```
