### ISSUE TITLE
Examine malformed CIK

### ISSUE THREAD

**Issue by iangow** [iangow-public/edgar#14]
CIKs are meant to be integers. But there appears to be a CIK value of `538467     2` in `edgar.filings`.

We should investigate. Is this an issue with the underlying index file on EDGAR? Or with our code to scraping this to populate `edgar.filings`?

**Comment by bdcallen** [comment]
@iangow I tried 
```r
dbGetQuery(pg, "SELECT * FROM edgar.filings WHERE cik = 5384672")
```
and
```r
dbGetQuery(pg, "SELECT * FROM edgar.filings WHERE cik = '538467 2' ")
```
and both returned empty data frames. 

I also tried puttting in ```538467 2``` into the search page for the EDGAR database, and got no results (page said no matching ticker symbol). Also just tried 5384672, and got no matching cik. How did you find this entry exactly?

**Comment by iangow** [comment]
It could be something in my database at `iangow.me`. Let me check.

**Comment by iangow** [comment]
I can't find this anywhere. Perhaps it was in an index file that was wiped on update.
