### ISSUE TITLE
Building the DB in OS (steps needed before running the code)

### ISSUE THREAD

**Issue by AdamZ2** [iangow-public/edgar#29]
Can you share the steps that we should do in OS to build and create the DB before using your programs. I have access to MacBook and I will use it to run your code. This program is very helpfull and will make people save a lot of time. We need only that you share the preparation steps before using it.
Can I have your personnal email?
Thanks

**Comment by iangow** [comment]
See [here](
https://iangow.wordpress.com/2015/09/13/installing-postgresql-9-4-using-macports/). This is a bit out of date, but should be easy to modify to use (say) `postgresql-10`.

**Comment by iangow** [comment]
1. Install MacPorts.
2. Install PostgreSQL:
```
sudo port install postgresql10 postgresql10-server
```
3. Follow instructions given in output from step 2 to set up a cluster.
4. Get PostgreSQL running.
```
sudo defaults write /Library/LaunchDaemons/org.macports.postgresql10-server.plist Disabled -bool false
sudo launchctl load /Library/LaunchDaemons/org.macports.postgresql10-server.plist
```
5. Set up a database, part 1.
```
sudo su - postgres
/opt/local/lib/postgresql10/bin/psql -U postgres -d template1
```
6. Set up a database, part 2. I create a user ID and a database that I own.
```
CREATE USER igow SUPERUSER CREATEDB CREATEROLE PASSWORD 'xxxxx';
CREATE DATABASE crsp OWNER igow;
```
