### ISSUE TITLE
Understand how TFN tables map to filings

### ISSUE THREAD

**Issue by iangow** [iangow-public/edgar#31]
Data in `tfn.table1` and `tfn.table2`.

**Comment by bdcallen** [comment]
@iangow The Thomson Reuters Insiders Data Feed Manual has a pretty good summary of tables 1 and 2. Table 1 contains information on transactions of non-derivative stock, and Table 2 contains information on derivative stock. Having had a look at some of the xml files, it seems many of the form 4's have either a non-trivial `<DerivativeTable>` (eg. [this](https://www.sec.gov/Archives/edgar/data/1000015/000120048303000002/0001200483-03-000002.txt)),  a non-trivial `<nonDerivativeTable>` (eg. [this](https://www.sec.gov/Archives/edgar/data/1011006/000117911012009035/edgar.xml)), or both (eg. [this](https://www.sec.gov/Archives/edgar/data/1200483/000111267911000086/edgar.xml)). In fact, in the latter example, there is a table of one of these types for each transaction reported under the [filing](https://www.sec.gov/Archives/edgar/data/1200483/000111267911000086/0001112679-11-000086-index.htm) (see the html for example).

Also there seem to be some numbers which Thomson Reuters have scraped which map to numbers on the pages of the filing. For instance, the `dcn` field of table 2 for this [filing](https://www.sec.gov/Archives/edgar/data/1000015/000120048303000002/0001200483-03-000002-index.htm), which is `03817287`, is exactly equal the `Film No.` listed on the html page, in the last section of details on the owner ('AMOROSO ALFRED J').

**Comment by bdcallen** [comment]
@iangow I've had a look at both tables for the example filing I gave above, with multiple transactions of both derivative and non-derivative stock. The `Film No.` for this is `111142681`, and doing 
```sql
SELECT * FROM tfn.table1 WHERE owner = 'AMOROSO ALFRED J' AND dcn = '111142681'
```
and 
```sql
SELECT * FROM tfn.table2 WHERE owner = 'AMOROSO ALFRED J' AND dcn = '111142681'
```,
one can see that there are 10 entries for this filing in table 1, and 5 entries in table 2 (sorry, not displaying the output since there are too many columns), corresponding to all the transactions in the filing. So each row of these tables corresponds to a single transaction from some filing, and thus there are generally multiple rows in each table for the one filing.

**Comment by bdcallen** [comment]
@iangow Also, curiously, in tables 1 and 2, there seem to be no columns with the accession numbers and cik's, although there are some fields `cusip6`, `cusip2` and `cusipx` which correspond with CUSIP numbers.

**Comment by iangow** [comment]
@bdcallen 

Don't worry about matching CUSIPs with CIKs for now. It's enough to know that the `tfn` tables do not include CIKs, as scraping data on CIKs is something of primary interest with these forms. I don't believe anything we have in the `edgar` tables maps to "film number" (and I believe we don't have any ID fields in common with the `tfn` data … this is a pain). I think we'd have to scrape film numbers if we wanted a solid link between `tfn` and `edgar` tables.
