### ISSUE TITLE
8-K identification of "transfer agents"

### ISSUE THREAD

**Issue by jamespkav** [iangow-public/edgar#32]
Thanks for the email response earlier Ben, although I'm not quite sure it solved the issue, as my home directory doesn't take me to where the `edgar/*` directory is. 

In general, as discussed with @iangow, I am looking to identify certain 8-K filings that come in `Item 5` (at this point, may expand).

Is it possible to download these filings and provide for me the `EDGAR_DIR`, which I think you should have set in your presets? @iangow might be able to help here with this directory if it has been moved. Thanks.

**Comment by iangow** [comment]
The EDGAR files are all in `/media/igow/2TB/` under `edgar/data/`, etc. I have issued a command to set ownership of these files to `igow:mccgr`. I believe that membership of `mccgr` should give you read and write access to the data (and you should already have read access).

**Comment by iangow** [comment]
It seems that @jamespkav and @bdcallen are members of `mccgr` on the MCCGR server:

```
igow@igow-z640:~$ groups jpk
jpk : jpk mccgr
igow@igow-z640:~$ groups bdcallen
bdcallen : bdcallen mccgr
```
