### ISSUE TITLE
Check incorrect datetime formats in transactionDate have been handled

### ISSUE THREAD

**Issue by bdcallen** [iangow-public/edgar#43]
@iangow 
If one does the query
```sql
SELECT COUNT(*) FROM edgar.forms345_table1 WHERE "transactionOrHolding" = 'Transaction' AND "transactionDate" IS NULL
```
one sees that there are currently 66 entries in `edgar.forms345_table1` where there are transactions with a null `transactionDate`.  If one looks at some of these filings, for instance this [one](https://www.sec.gov/Archives/edgar/data/1029623/000076999312000640/0000769993-12-000640-index.htm), and looks at the xml file, one sees segments for the `transactionDate` node that look like this

```xml
<transactionDate>
<value>2012-12-11-05:00</value>
</transactionDate>
```

Previously, my code just used the function `ymd` from the lubridate package on the `transactionDate` value to convert from the string format to datetime format, but was failing for these entries. Since, then I have written a function `extract_date`

```r
extract_date <- function(string) {

    if(is.na(string)) {

        return(ymd(string, quiet = TRUE))

    } else {reg_match <- regexpr('[0-9]{4}[ -/]*[0-9]{1,2}[ -/]*[0-9]{1,2}', string)
    date <- ymd(regmatches(string, reg_match), quiet = TRUE)

    return(date)

    }
}
```
which first extracts the year-month-day form from the string format using a regular expression, and then uses `ymd`. So all that is left to do here is to check that these cases are being handled once we start downloading the data for all the filings again.

**Comment by iangow** [comment]
You could probably just use `ymd(substring(string, 1, 10)`. But whatever works.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by bdcallen** [comment]
@iangow I've rewritten the code to use `extract_date` to handle these cases, and it works well. We can close this one too.
