### ISSUE TITLE
Handle alternative entries for Boolean variables in the xml documents 

### ISSUE THREAD

**Issue by bdcallen** [iangow-public/edgar#44]
@iangow There are also some filings, like this [one](https://www.sec.gov/Archives/edgar/data/1456865/000147793216013336/0001477932-16-013336-index.htm), for which the entries for Boolean variables are written as strings such "true" and "false", rather than the usual `0/1` format
```xml
<reportingOwnerRelationship>
<isDirector>false</isDirector>
<isOfficer>false</isOfficer>
<isTenPercentOwner>true</isTenPercentOwner>
<isOther>false</isOther>
```
I will amend the code to handle these cases.

**Comment by iangow** [comment]
Depending on how these are parsed (as strings or integers for `0`/`1`), as simple `as.logical()` may work to handle both cases.

```r
> as.logical("true")
[1] TRUE
> as.logical("false")
[1] FALSE
> as.logical("1")
[1] NA
> as.logical(1)
[1] TRUE
> as.logical(0)
[1] FALSE
> as.logical("0")
[1] NA
```

**Comment by bdcallen** [comment]
@iangow I also realised the above when using `as.logical`. The function I wrote `string_to_boolean` handles both these cases
```r
string_to_boolean <- function(string) {

    # first strip spaces from string

    reduced_string <- gsub("[ \t\n\r]", '', string)

    if(grepl("^[01]$", reduced_string)) {

        return(as.logical(as.integer(reduced_string)))

    } else {

        return(as.logical(reduced_string))

    }


}
```

Furthermore, I use `string_to_boolean` on the logical columns in the functions which scrape these dataframes for the tables (`get_header`, `get_derivative_df`, `get_nonDerivative_df`, and so on), to make the appropriate conversions. 

Thus, we can close this one as well now.
