### ISSUE TITLE
Fix permissions on tables

### ISSUE THREAD

**Issue by iangow** [iangow-public/edgar#6]
Grant ownership to `edgar` and read access to `edgar_access`.

**Comment by jingyujzhang** [comment]
I fixed 
`aaer.name_link`,` audit_analytics.feed39_aaer24`, `fund_beta.fundann_vars_new`, `nonans_product.executives`, `streetevents.manual_permno_matches`.

I don't have permission to run the following.
```sql
GRANT USAGE ON SCHEMA glassdoor TO glassdoor_access;
GRANT USAGE ON SCHEMA hoberg_phillips TO hoberg_phillips_access;
GRANT USAGE ON SCHEMA patents TO patents_access;
GRANT USAGE ON SCHEMA sec_enforce TO sec_enforce_access;
```

**Comment by iangow** [comment]
> I fixed 
> `aaer.name_link`,` audit_analytics.feed39_aaer24`, `fund_beta.fundann_vars_new`, `nonans_product.executives`, `streetevents.manual_permno_matches`.
> 
> I don't have permission to run the following.
> ```sql
> GRANT USAGE ON SCHEMA glassdoor TO glassdoor_access;
> GRANT USAGE ON SCHEMA hoberg_phillips TO hoberg_phillips_access;
> GRANT USAGE ON SCHEMA patents TO patents_access;
> GRANT USAGE ON SCHEMA sec_enforce TO sec_enforce_access;
> ```

I ran these:

```
192-168-1-7:~ igow$ psql -h aaz.chicagobooth.edu -d postgres
psql (9.6.5, server 9.4.12)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.

postgres=# GRANT USAGE ON SCHEMA glassdoor TO glassdoor_access;
GRANT
postgres=# GRANT USAGE ON SCHEMA hoberg_phillips TO hoberg_phillips_access;
GRANT
postgres=# GRANT USAGE ON SCHEMA patents TO patents_access;
GRANT
postgres=# GRANT USAGE ON SCHEMA sec_enforce TO sec_enforce_access;
GRANT
postgres=# 
```
But this does not fix the problem in the original code. If that code is re-run than these permission fixes (and the ones @jingyujzhang ran) will be broken.

So I think we need to identify the code that creates the tables and put code in there. For example, I fixed `streetevents.manual_permno_matches` with a commit [here](https://github.com/iangow/streetevents/commit/ccec4f3a8a5254e32028dc3adb27b043f0a7b52b). Most of the other tables relate to projects I'm not involved with.

**Comment by jingyujzhang** [comment]
>I fixed
aaer.name_link,audit_analytics.feed39_aaer24, fund_beta.fundann_vars_new, nonans_product.executives, streetevents.manual_permno_matches.

I fixed code for the first 4 tables, and Ian fixed the last one.

This issue can be closed.

**Comment by iangow** [comment]
It is helpful to refer to the issue in the commits. 

Note that you can do this across repositories by including the full URL. See my commit message [here](https://github.com/iangow/streetevents/commit/ccec4f3a8a5254e32028dc3adb27b043f0a7b52b), which creates a link above.

**Comment by jingyujzhang** [comment]
azakolyukina/aaer#5
azakolyukina/audit_analytics#15
azakolyukina/nonans_product#49
azakolyukina/fund_beta@78ac01d1d472516dfff8f00ba095dd8810de8890
