### ISSUE TITLE
Scrape "last modified" data for index files.

### ISSUE THREAD

**Issue by iangow** [iangow-public/edgar#9]
See [here](https://www.sec.gov/Archives/edgar/full-index/1993/QTR1/) for an example.

Basic idea is to create a data frame with `year`, `quarter`, and `last_modified` columns.

**Comment by iangow** [comment]
@bdcallen I made this into an issue as a way of tracking things and keeping things focused. Once you get this going, we could go to the next step (the remaining steps should be pretty easy if you can get this one working).

**Comment by bdcallen** [comment]
@iangow I've finished two functions, getLastUpdate and makeUpdatesDataframe which make the desired data frame. The function getLastUpdate

**Comment by bdcallen** [comment]
@iangow I've finished a couple of functions which make the desired data frame. The function getLastUpdate

**Comment by bdcallen** [comment]
@iangow I've finished a couple of functions which produce the desired data frame. The function getLastUpdate(year, quarter)

``

**Comment by bdcallen** [comment]
@iangow I've finished a couple of functions which produce the desired data frame. The function getLastUpdate(year, quarter)
````

**Comment by bdcallen** [comment]
@iangow I have finished a couple of functions which produce the desired data frame. The function getLastUpdate

`getLastUpdate <- function(year, quarter) {
    
    library(rvest)
    library(lubridate)
    # Scrape the html table from the website for the given year and quarter
    filetbl <- read_html(paste("https://www.sec.gov/Archives/edgar/full-index/",
                               year,"/QTR", quarter, "/",sep="")) %>% html_nodes("table") %>% .[[1]] %>% html_table()
    colnames(filetbl)[[3]] <- "Last_Modified"
    
    # company.gz corresponds to the first row of the html table, so take the first element of filetbl$Last_Modified
    # to return the date of the last update for the year and quarter
    return(mdy_hms(filetbl$Last_Modified[1], tz = "UTC"))
    
    
}`

gets the time of the last modification to the file company.gz for the given year and quarter, scraped from the SEC website.

The function makeUpdatesDataframe

`makeUpdatesDataframe <- function() {
    
    library(lubridate)
    library(dplyr)
    
    date <- today(tz = "UTC")
    numrows <- (year(date) - 1993) * 4 + quarter(date)
    index <- 1:numrows
    years <- 1993 + (index - 1)%/%4L
    quarters <- 1 + (index - 1)%%4L
    updates <- data.frame(year = years, quarter = quarters)
    updates <- updates %>% rowwise() %>% mutate(last_modified = getLastUpdate(year, quarter))
    updates$year <- as.integer(updates$year)
    updates$quarter <- as.integer(updates$quarter)
    return(updates)
    
}`

the applies getLastUpdate to each row of a dataframe updates, which initially has two columns year and quarter, to produce the last_modified column, and then returns the data frame. All times are assumed to be in UTC

**Comment by iangow** [comment]
@bdcallen Thanks. I committed your code. I then modified and expanded on it. See the two commits above. Still a little work to be done to actually get the index files using the results of this. 

It may make sense to put the functions from `get_filings.R` into a separate file that can be `source()`ed by other files (a bit like `import some_function from get_filings` in Python).

**Comment by iangow** [comment]
And here's the same thing in SQL:

```sql
igowmbp15:~ igow$ psql -h iangow.me -d crsp
psql (9.6.5, server 9.6.7)
Type "help" for help.

crsp=# SET time zone 'Australia/Melbourne';
SET
crsp=# SELECT * FROM edgar.index_last_modified WHERE year=1994 AND quarter=3;
 year | quarter |     last_modified      
------+---------+------------------------
 1994 |       3 | 2014-04-17 06:00:10+10
(1 row)

crsp=# SET time zone 'America/New_York';
SET
crsp=# SELECT * FROM edgar.index_last_modified WHERE year=1994 AND quarter=3;
 year | quarter |     last_modified      
------+---------+------------------------
 1994 |       3 | 2014-04-16 16:00:10-04
(1 row)
```

Note that the original text scraped from the site is `04/16/2014 04:00:10 PM`.
